config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  get 'categories/index'
  namespace :admin do   #adminを追加するために追加された。
    get 'home', to:'pages#home'
    resources :users 
    resources :categories do
      resources :words
    end
  end

  root 'pages#home' #初めから表示されるページ。
  get "/about" =>  "pages#about"
  get "/signup"  =>  "users#new"
  
  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  get '/index' , to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :categories
  resources :relationships

  resources :lessons do
    resources :answers
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
    belongs_to :action,polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :lesson
    belongs_to :word
    belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words
  has_many :lessons, dependent: :destroy
end

app/models/choice.rb
#choiceはwordと繋がっている（belongs_to）

class Choice < ApplicationRecord
    belongs_to :word
    validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :answers, dependent: :destroy
    has_many :words, through: :answers
    has_many :choices,through: :answers
    has_one :activity, as: :action


    def next_word
        (category.words - words).first
    end

    def lesson_results
       choices.where(correct: true).count
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
    has_one :activity, as: :action

    after_create :relationship_activity
    def relationship_activity
        create_activity(user: follower)
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 3, maximum: 65 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 3 },allow_nil:true

  mount_uploader :avatar, AvatarUploader

  has_many :active_relationships, class_name: "Relationship",
              foreign_key: "follower_id",
              dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship",
              foreign_key: "followed_id",
              dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons,dependent: :destroy

  has_many :activities, dependent: :destroy

  def active_relationships
    Relationship.where(follower_id: id)
    # follower_id = id
end

def passive_relationships
    Relationship.where(followed_id: id)
end

def follow(other_user)
    Relationship.create(
      follower_id: id,
      followed_id: other_user.id
    )
end

def relationship(other_user)
  active_relationships.find_by(
    followed_id: other_user.id
  )
end

def lesson_taken(cat_id)
    lesson = lessons.find_by(category_id: cat_id)
end
end

app/models/word.rb
# has_manyでどこと繋がっているのか。

class Word < ApplicationRecord
  belongs_to :category
  validates :content, presence: true 
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices
  validate :has_one_correct_answer, :has_unique_choices

  def correct_answer
    choices.find_by(correct:true).try(:content)
  end 

  def has_one_correct_answer
     if choices.select{ |choice| choice.correct? }.count != 1
      return errors.add :base,"Must have one correct choice"
     end
  end

  def has_unique_choices
      if choices.uniq{|choice| choice.content }.count < choices.length
        return errors.add :base,'Must have unique choices'
      end
  end
end

#def has_one_correct_answerは選択肢を1つしか洗濯してはいけない

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
    if signed_in?
      @activities = Activity.where("user_id IN (?) OR user_id =?", current_user.following_ids,current_user.id).paginate(page: params[:page],per_page:10)
      render 'users/dashboard'
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  # Show all users
  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Welcome to Sakata Elearning System" #saveが完了した時に画面に出る。
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    # Finding the specific user to EDIT
    @user = User.find(params[:id])
  end
  
  # Button for Updating profile
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(users_params)
      # If successful UPDATE, this will happen
      flash[:success] = "Successfully Update" 
      redirect_to root_url# Goes to Profile
    else
      #  If user doesn't input anything, render Edit again
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities=@user.activities.paginate(page: params[:page],per_page:10)
  end

  
  
  private
    def users_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,:avatar)
    end
  end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/crudcategories_helper.rb
module CrudcategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
      
    # Lets users sign in, session is stored in db
  def sign_in(user)
    session[:user_id] = user.id
  end

  # Deleting the session and user_id in db
  def sign_out
    session.delete(:user_id)
  end

  # Defining who is currently logged in
  def current_user
    User.find_by(id: session[:user_id])
    # takes coordination between your user’s browser and your Rails app to make everything connect up
    # it all starts with cookies
  end

  # Asking Rails on if user is signed in
  def signed_in?
    !current_user.nil?
    # Rails will check if the user is nil/null
    # Rails will check if there is no user (user is empty)
  end
end

app/helpers/users_helper.rb
module UsersHelper  #アバターの追加はhelperページで行った
  def user_avatar(user,classess)
   @avatar = user.avatar
   if @avatar.present?
      @avatar_user = image_tag(@avatar.url, class: classess)
   else
       @avatar_user = image_tag("default.png", class: classess)
   end
  end
end

#①helperページでメゾットの追加
#②if文を使いデフォルトを使う場合と使わない場合とで分ける
#③showページに行き、デフォルトを表示させる。

app/views/admin/pages/home.html.erb
     <p></p>
    <div class="container">
      <div class="card card-class">
        <div class="jumbotron">
         <div  class="text-center">
          <strong><p class="card-text">Admin page</p></strong>
         </div>
           
            <div class="media-body">
            　　<div class =row>
                  <div class=col-sm-6>
                   <div class="text-center">
                     <%= link_to "Categories" ,admin_categories_path, class: 'btn btn-default'%>
                     <p>You can change the categories,descriptions,words,answers and choices.</p> 
                   </div>
            　　  </div>
               
                 <div class=col-sm-6>
                  <div class="text-center">
                   <%= link_to "Users", admin_users_path, class:'btn btn-default'  %>
                   <p>Yuu can add or remove the administration to users.</p>
                  </div>
                 </div>
                </div>
                <div class ="text-center"><%= button_to "Back to home" %></div>
            </div>
          </div>
        </div>
    </div>

app/views/layouts/_header.html.erb
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"><nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <!--heater-->
        <ul class="navbar-nav mr-auto">
          <a class="navbar-brand text-left" href="#">Sakata-e-learning</a>
        </ul>
        <ul class="navbar-nav">  
            <% if signed_in? %>  <!--もしサインインしたら、headerが変わるしくみ　ifを使う-->
             <li class="nav-item">
                <%= link_to "HOME", root_path ,class: "nav-link" %>      <!--アカウント管理を表示 -->        
              </li>
            <li class="nav-item">
                <%= link_to "ABOUT", about_path ,class: "nav-link" %>        <!--about-->     
            </li>

            <li class="nav-item">
                <%= link_to "LESSONS", categories_path ,class: "nav-link" %>        <!--about-->     
            </li>
                <li class="nav-item">
                    <%= link_to "USERS", users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbar-dropdown" data-toggle="dropdown">
                        <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu">
                        <%= link_to "PROFILE", current_user, class: "dropdown-item" %>
                        <%= link_to "EDIT PROFILE", edit_user_path(current_user), class: "dropdown-item" %>
                        <%= link_to "LOGOUT", signout_path, method: :delete, class: "dropdown-item" %>
                    </div>
                </li>
            <% else %>　<!--signできなかった時にここにくる-->
               <li class="nav-item">
                <%= link_to "HOME", root_path ,class: "nav-link" %>      <!--アカウント管理を表示 -->        
              </li>
                <li class="nav-item">
                    <%= link_to "USERS", users_path, class: "nav-link" %>
                </li>
                
                <li class="nav-item">
                    <%= link_to "SIGN UP", signup_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "SIGN IN", signin_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SakataElearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if flash.any? %> <!--これでusersコントローラーで定義したflashメッセージを表示する-->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error-message.html.erb
<% if object.errors.any? %>  <!--もし、エラーが出たら表示する,validatesでの定義も忘れずに-->
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feeds.html.erb
<% if @activities.any? %>
    <% @activities.each do |activity| %>
        <div class="row mt-4">
            <div class="col-3">
            <%= user_avatar(activity.user,"feed-img-size")%>
            </div>
        
            <div class="col-9">
            <% if activity.action_type=="Lesson" %>
                <% if activity.user == current_user %>
                    <p><%= link_to "You ", user_path(current_user)%>learned
                        <%= activity.action.result%> of <%= activity.action.category.words.count %>
                        in <%= link_to activity.action.category.title,lesson_path(activity.action.id) %>
                    </p>
                <% else%>
                    <p><%= link_to activity.user.name, user_path(activity.user)%> learned
                        <%= activity.action.result%> of <%= activity.action.category.words.count %>
                        in <%= link_to activity.action.category.title,lesson_path(activity.action.id) %>
                    </p>
                <%end%>
                        
            <% elsif activity.action_type=="Relationship"%>
                <% followed_user = User.find_by(id: activity.action.followed_id) %>
                <% if activity.user == current_user %>
                    <p><%= link_to "You",user_path(current_user) %> followed
                        <%= link_to followed_user.name,user_path(followed_user)%>
                    </p>
                <%else%>
                    <p><%= link_to activity.user.name,user_path(activity.user) %> followed
                    <%= link_to followed_user.name,user_path(followed_user)%>
                    </p>
                <%end%>
            <%end%>
            <span>
                <small><%= time_ago_in_words(activity.created_at) %> ago. </small>
            </span>
            </div>
        </div>
    <%end%>
<% else %>
  <h5>Nothing to show </h5>
<% end %>