config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  get 'categories/index'
  namespace :admin do   #adminを追加するために追加された。
    get 'home', to:'pages#home'
    resources :users 
    resources :categories do
      resources :words
    end
  end

  root 'pages#home' #初めから表示されるページ。
  get "/about" =>  "pages#about"
  get "/signup"  =>  "users#new"
  
  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  get '/index' , to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :categories
  resources :relationships

  resources :lessons do
    resources :answers
  end
end

app/models/word.rb
# has_manyでどこと繋がっているのか。

class Word < ApplicationRecord
  belongs_to :category
  validates :content, presence: true 
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices
  validate :has_one_correct_answer, :has_unique_choices

  def correct_answer
    choices.find_by(correct:true).try(:content)
  end 

  def has_one_correct_answer
     if choices.select{ |choice| choice.correct? }.count != 1
      return errors.add :base,"Must have one correct choice"
     end
  end

  def has_unique_choices
      if choices.uniq{|choice| choice.content }.count < choices.length
        return errors.add :base,'Must have unique choices'
      end
  end
end

#def has_one_correct_answerは選択肢を1つしか洗濯してはいけない

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  #read the loggged in and admin user method before running the controller
  before_action :logged_in_user
  before_action :admin_user
  #timesメゾットを使っている
  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build
    3.times {@word.choices.build}
  end

    # Show all Category
  def index
    #@word = Word.all
    @category= Category.find(params[:category_id])
    @words = @category.words.paginate(page: params[:page], per_page: 10)

  end
  
  def create
    @category= Category.find(params[:category_id])
    @word = @category.words.build(word_params)
    if @word.save
      flash[:success] = "Successfully Created Words" #saveが完了した時に画面に出る。
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def edit
    @category= Category.find(params[:category_id])
    @word=Word.find(params[:id])
  end
  
  def update
    @category= Category.find(params[:category_id])
    @word=Word.find(params[:id])
    if @word.update(word_params)
      flash[:success] = "Successfully Created Word" #saveが完了した時に画面に出る。
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def show
    @category = Category.new
  end

  def destroy
    @category= Category.find(params[:category_id])
    @word=Word.find(params[:id])
    @word.delete
    flash[:success] = "Successfully deleted" 
    redirect_to admin_category_words_url
  end
  
  private
    def word_params
      params.require(:word).permit(:content,choices_attributes: [:id,:content,:correct])
    end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @category, @word] do |f| %>
   <%= render 'shared/error-message', object: @word %>
   <div clsaa="form-group">
     <%=f.label :content,"word"%>
     <%=f.text_field :content, class: "form-control" %>
     <br><hr>
   </div>

   <div class="form-group">
      <% label_tag"Choices"%>
      <%= f.fields_for :choices do |choice|%>
         <%= choice.text_field :content,class:"form-control"%>
         <%= choice.check_box :correct,class: "d-inline"%>
         <p class="d-inline">This is the correct answer!</p>
      <%end%>
   </div>
   <%= f.submit msg,class:"btn btn-primary"  %>
<%end%>

app/views/admin/words/create.html.erb
<h1>Admin::Words#create</h1>
<p>Find me in app/views/admin/words/create.html.erb</p>

app/views/admin/words/edit.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">edit Word</h1>
  <%=render 'form.html', msg: "update a category" %>
</div>

app/views/admin/words/index.html.erb
<div class="row">

    <div class="col-8 mt-4 mx-auto">
        <div class="row">
            <div class="col-sm text-center">
                <strong><h1><%= @category.title %></h1></strong>
                <h4><%= @category.description %></h4>
            </div>
            <div class="col-sm">
                <%= link_to "New Word",  new_admin_category_word_path , class: "btn btn-info float-right"%>
            </div>

        <table class="table mt-3 table-bordered text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Word</th>
                    <th scope="col">Answer</th>
                    <th scope="col">Settings</th>
                </tr>
            </thead>
            <tbody>
                <% @words.each do |word| %>
                    <tr>
                        <td><%= word.content %></td>
                        <td><%= word.correct_answer %></td>
                        <td>
                            <%= link_to 'Edit', edit_admin_category_word_path(@category, word) %> /
                            <%= link_to 'Delete', admin_category_word_path(@category, word), method: :delete, data: { confirm: "Are your sure?"} %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>

        <div class="paginate">
            <%= will_paginate @word %>
        </div>

        <%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
        <br> <br> <br> <br>
    </div>  
</div>

app/views/admin/words/new.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">New Words</h1>
    <%=render 'form', msg: "Create a word" %>
</div>