config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  get 'categories/index'
  namespace :admin do   #adminを追加するために追加された。
    get 'home', to:'pages#home'
    resources :users 
    resources :categories do
      resources :words
    end
  end

  root 'pages#home' #初めから表示されるページ。
  get "/about" =>  "pages#about"
  get "/signup"  =>  "users#new"
  
  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  get '/index' , to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :categories
  resources :relationships

  resources :lessons do
    resources :answers
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 3, maximum: 65 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 3 },allow_nil:true

  mount_uploader :avatar, AvatarUploader

  has_many :active_relationships, class_name: "Relationship",
              foreign_key: "follower_id",
              dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship",
              foreign_key: "followed_id",
              dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons,dependent: :destroy

  has_many :activities, dependent: :destroy

  def active_relationships
    Relationship.where(follower_id: id)
    # follower_id = id
end

def passive_relationships
    Relationship.where(followed_id: id)
end

def follow(other_user)
    Relationship.create(
      follower_id: id,
      followed_id: other_user.id
    )
end

def relationship(other_user)
  active_relationships.find_by(
    followed_id: other_user.id
  )
end

def lesson_taken(cat_id)
    lesson = lessons.find_by(category_id: cat_id)
end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  #read the loggged in and admin user method before running the controller
  before_action :logged_in_user
  before_action :admin_user
  

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def update
    @user=User.find(params[:id])
    @user.update(admin: true)

    redirect_to admin_users_url
  end

  def destroy
    @user= User.find(params[:id])
    @user.update(admin: false)

    redirect_to admin_users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  # Show all users
  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Welcome to Sakata Elearning System" #saveが完了した時に画面に出る。
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    # Finding the specific user to EDIT
    @user = User.find(params[:id])
  end
  
  # Button for Updating profile
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(users_params)
      # If successful UPDATE, this will happen
      flash[:success] = "Successfully Update" 
      redirect_to root_url# Goes to Profile
    else
      #  If user doesn't input anything, render Edit again
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities=@user.activities.paginate(page: params[:page],per_page:10)
  end

  
  
  private
    def users_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,:avatar)
    end
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper  #アバターの追加はhelperページで行った
  def user_avatar(user,classess)
   @avatar = user.avatar
   if @avatar.present?
      @avatar_user = image_tag(@avatar.url, class: classess)
   else
       @avatar_user = image_tag("default.png", class: classess)
   end
  end
end

#①helperページでメゾットの追加
#②if文を使いデフォルトを使う場合と使わない場合とで分ける
#③showページに行き、デフォルトを表示させる。

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 <%= render 'shared/error-message', object: f.object %> 
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>      
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class:"form-control" %>     
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>     
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class:"form-control" %>     
    </div>
    <div class="form-group">
      <%= f.label :avatar %>
      <%= f.file_field :avatar, class:"form-control" %>     
    </div>
    <p></p>
    <div class="form-group">
      <%= f.submit msg,class:"btn btn-primary", class:"form-control" %>
    </div>

<% end %>

app/views/users/dashboard.html.erb
<div class="container">
    <div class="row mt-4">
    <div class="col-sm-4">
        
         <div class="card">　<!--card化をして要素をまとめた-->
            <div class="card-header">
                User Info
            </div>
            <div class="card-body text-center">
                <h1><%= current_user.name %></h1>
                <%= user_avatar(current_user,"img-size")%>　<!--user_avatarの引数に@userを入れる-->
                <hr>
              <div class="row mt-3"> <!--rowの中にcolが格納されている。-->
                <div class="col-sm-6"> <!--smはsmallの略称-->
                 <a href="#">
			      <strong><%= link_to current_user.active_relationships.count, "#" %></strong> 
			     </a>
                  <div>followers</div>
                </div>	

                <div class="col-sm-6">
		         <a href="#">
			      <strong>  <strong><%= link_to current_user.passive_relationships.count, "#" %></strong> </strong> 
			     </a>
                  <div>following</div>	
                </div>
               </div>
            </div> 
        </div>
    </div>

	<div class="col-sm-8">　<!--card化をして要素をまとめた-->
        <div class="card">
            <div class="card-header">
                Activity Feed
            </div>
            <div class="card-body">
                <hr>
                <%=render 'shared/feeds' %>
            </div>
            <div class="paginate mt-3 text-center">
                <%= will_paginate @activities %>
            </div>
        </div>       
	</div>
    </div>

  
</div> 

app/views/users/edit.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">Edit profile</h1>
  <%=render 'users/form.html', msg: "Update Profile" %>  <!--new,editのviewは同じだったのでまとめた、msgでコメントを出す-->
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>　 <!--application.htmlのyield側から呼び出すことができる。-->
<h1 class="text-center">All users</h1>

<%# How to call pagination %>
<div class=text-center>
 <div class="paginate mb-3 ">
    <%= will_paginate @users %>
 </div>

 <div class="row">
    <% @users.each do |user| %>
        <div class="col-md-6 mb-2">
          
            <%= link_to user.name, user_path(user.id) %>
        </div>
    <% end %>
 </div>

 <div class="paginate my-3">
    <%= will_paginate @users %>
 </div>
</div>

app/views/users/login.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">log-in</h1>
 
 <%= render 'shared/error-message' %>

<%= form_tag("/login") do  %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :name, class:"form-control" %>     
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>     
    </div>

    <p></p>
    <div>
    <%= f.submit "create new account",class:"btn btn-primary", class:"form-control" %>
    </div>
<% end %>

</div>

app/views/users/new.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">Sign up</h1>
  <%=render 'users/form.html', msg: "Create an account" %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row mt-4">
    <div class="col-sm-4">
        
         <div class="card">　<!--card化をして要素をまとめた-->
            <div class="card-header">
                User Info
            </div>
            <div class="card-body text-center">
                <h1><%= @user.name %></h1>
                <div class="text-center">
                <%= user_avatar(@user,"img-size")%>　<!--user_avatarの引数に@userを入れる-->
                </div>
                <p></p>
                  <%if current_user.admin? && @user == current_user%>
                   <%= link_to "Admin", admin_home_path,class: "btn btn-primary"%>
                  <%end%>
                  <% unless current_user == @user %>
                    <% unless current_user.relationship(@user) %>
                        <%= button_to "Follow", relationships_path,
                                            params: {followed_id: @user.id},
                                            class: "btn btn-sm btn-success mt-4" %>
                    <% else %>
                        <%= button_to "Unfollow", relationship_path(current_user.relationship(@user)),
                                            method: :delete,
                                            class: "btn btn-sm btn-danger mt-4" %>
                    <% end %>
                <% end %>
                <hr>
              <div class="row mt-3"> <!--rowの中にcolが格納されている。-->
                <div class="col-sm-6"> <!--smはsmallの略称-->
                 <a href="#">
			      <strong><%= link_to @user.active_relationships.count, "#" %></strong> 
			     </a>
                  <div>followers</div>
                </div>	

                <div class="col-sm-6">
		         <a href="#">
			      <strong>  <strong><%= link_to @user.passive_relationships.count, "#" %></strong> </strong> 
			     </a>
                  <div>following</div>	
                </div>
               </div>
            </div> 
        </div>
    </div>

	<div class="col-sm-8">　<!--card化をして要素をまとめた-->
        <div class="card">
            <div class="card-header">
                Activity Feed
            </div>
            <div class="card-body">
                <hr>
                <%=render 'shared/feeds' %>
                <div class="paginate mt-3 text-center">
                    <%= will_paginate @activities %>
                </div>
            </div>
        </div>       
	</div>
    </div>
</div> 