config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  get 'categories/index'
  namespace :admin do   #adminを追加するために追加された。
    get 'home', to:'pages#home'
    resources :users 
    resources :categories do
      resources :words
    end
  end

  root 'pages#home' #初めから表示されるページ。
  get "/about" =>  "pages#about"
  get "/signup"  =>  "users#new"
  
  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  get '/index' , to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :categories
  resources :relationships

  resources :lessons do
    resources :answers
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words
  has_many :lessons, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  #read the loggged in and admin user method before running the controller
  before_action :logged_in_user
  before_action :admin_user

  def new
    @category = Category.new
  end

    # Show all Category
  def index
    #@category = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Successfully Created Category" #saveが完了した時に画面に出る。
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def edit
    # Finding the specific Gcategory to EDIT
    @category = Category.find(params[:id])
  end
  
    # Button for Updating profile
  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(category_params)
      # If successful UPDATE, this will happen
      flash[:success] = "Successfully Update" 
      redirect_to admin_categories_url
    else
      #  If user doesn't input anything, render Edit again
      render 'edit'
    end
  end

  def show
    @category = Category.new
  end

  def destroy
    @category = Category.find(params[:id])
    @category.delete
    flash[:success] = "Successfully deleted" 
    redirect_to admin_categories_url
  end
  
  private
  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories= Category.paginate(page: params[:page], per_page: 10)
  end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
 <%= render 'shared/error-message', object: f.object %> <!--error-messageからファイルを持ってくる。-->
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>      
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class:"form-control" %>     
    </div>
    <p></p>
    <div class="form-group">
      <%= f.submit msg,class:"btn btn-primary", class:"form-control" %>
    </div>

<% end %>

app/views/admin/categories/destroy.html.erb
<div class="jumbotron text-center">
    <h1 class="display">
        Have deleted
    </h1>
      <a class="btn" href="users_url">Go to Categories</a>
</div>

app/views/admin/categories/edit.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">edit category</h1>
  <%=render 'form.html', msg: "update a category" %>
</div>

app/views/admin/categories/index.html.erb
<h1 class="text-center">All categories</h1>

<%# How to call pagination %>

<div class="container">
    <div class=text-center>
        <div class="text-right">
            <%= link_to 'New Category',new_admin_category_path,class: "btn btn-primary"%>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered mt-4">
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>action</th>
                    </tr>
                    <% @categories.each do |category| %>
                    <tr>
                        <td><%= link_to category.title, admin_category_words_path(category)%></td>
                        <td><%= link_to category.description, "#"%></td>
                        <td>
                            <%= link_to "|edit|", edit_admin_category_path(category) %>
                            <%= link_to "|delete|", admin_category_path(category), method: :delete %> 
                        </td>
                    </tr>
                    <% end %>
                </table> 
                <div class="paginate mb-3 ">
                    <%= will_paginate @categories %>
                </div>
                    <%= link_to 'Back', admin_categories_path, class: "btn btn-primary" %>
                <br> <br> <br> <br>
            </div>
        </div>
    </div>
</div>

app/views/admin/categories/new.html.erb
<div class="col-6 mx-auto">
<h1 class="text-center">New Category</h1>
  <%=render 'form.html', msg: "Create a category" %>
</div>

app/views/admin/categories/update.html.erb
<div class="jumbotron text-center">
    <h1 class="display">
        Congratulation! Have edtited!
    </h1>
      <a class="btn" href="/categories">Go to Categories!</a>
</div>